dqi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: dqi
      password: dqi
      dbname: dqi
      schema: analytics
      threads: 4
      connect_timeout: 15
