dqi:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: atlas
      password: atlas
      dbname: atlas
      schema: analytics
      threads: 4
      connect_timeout: 15
    prod:
      type: postgres
      host: db
      port: 5432
      user: postgres
      password: postgres
      dbname: dashboard
      schema: analytics
      threads: 4
      connect_timeout: 15
