version: 2

models:
  - name: orders
    description: "Order information derived from invoices"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: order_number
        description: "Invoice number used as order identifier"
      - name: class
        description: "Class categorization"
      - name: terms
        description: "Payment terms"
      - name: status
        description: "Order status"
      - name: po_number
        description: "Purchase Order number"
        
  - name: companies
    description: "Extracted company information from customer data"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: company_domain
        description: "Company domain extracted from email"
      - name: company_name
        description: "Company name from CSV"
        
  - name: customers
    description: "Customer information with company references"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Customer name from CSV"
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: customer_type
        description: "Type of customer (e.g., Retail, US Customer)"
      - name: company_domain
        description: "Company domain reference"
      - name: company_name
        description: "Company name reference"
