version: 2

models:
  - name: orders
    description: "Order information derived from invoices and sales receipts"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: order_number
        description: "Invoice number or Sales Receipt number used as order identifier"
      - name: order_type
        description: "Type of order (invoice or sales_receipt)"
      - name: class
        description: "Class categorization"
      - name: terms
        description: "Payment terms"
      - name: payment_method
        description: "Payment method"
      - name: status
        description: "Order status"
      - name: po_number
        description: "Purchase Order number"
      - name: order_date
        description: "Invoice date or Sales Receipt date (PostgreSQL DATE type)"
      - name: total_amount
        description: "Total amount from invoice or sales receipt"
      - name: customer_name
        description: "Customer name from the source data"
        
  - name: order_items
    description: "Line items from sales receipts and invoices linked to their parent orders"
    columns:
      - name: order_id
        description: "Reference to orders.quickbooks_id"
        tests:
          - not_null
      - name: order_number
        description: "Invoice number or Sales Receipt number"
        tests:
          - not_null
      - name: order_type
        description: "Type of order (invoice or sales_receipt)"
        tests:
          - not_null
      - name: product_code
        description: "Product or service code/name"
      - name: product_description
        description: "Description of the product or service"
      - name: quantity
        description: "Quantity ordered"
      - name: unit_price
        description: "Unit price of the product or service"
      - name: line_amount
        description: "Total amount for this line item"
      - name: product_class
        description: "Classification of the product or service"
      - name: service_date
        description: "Service date if applicable"
      - name: sales_tax_code
        description: "Sales tax code for the product or service"
        
  - name: companies
    description: "Unique company records identified by email domain"
    columns:
      - name: company_id
        description: "Surrogate key for the company (MD5 hash of company domain)"
        tests:
          - not_null
          - unique
      - name: company_name
        description: "Original company name"
      - name: customer_name
        description: "Customer name associated with the company"
      - name: company_domain
        description: "Email domain used to identify the company"
      - name: created_at
        description: "Date when the record was created (from customer's Created Date or current date)"
        
  - name: customers
    description: "Customer information with company references"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Customer name from CSV"
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: customer_type
        description: "Type of customer (e.g., Retail, US Customer)"
      - name: company_id
        description: "Reference to companies.company_id"
        
  - name: company_stats
    description: "Aggregated statistics for companies including customer counts and order totals"
    columns:
      - name: company_id
        description: "Reference to companies.company_id"
        tests:
          - not_null
          - unique
      - name: customer_count
        description: "Count of distinct customers associated with this company"
      - name: total_orders
        description: "Sum of all order amounts for this company's customers"
        
  - name: products
    description: "Product information derived from items"
    columns:
      - name: item_name
        description: "Name of the item/product"
        tests:
          - not_null
          - unique
      - name: sales_description
        description: "Description of the item/product for sales purposes"
        
  - name: item_history
    description: "Historical record of changes to item attributes"
    columns:
      - name: item_name
        description: "Name of the item/product (reference to products.item_name)"
        tests:
          - not_null
      - name: column_name
        description: "Name of the column that changed (e.g., purchase_cost, sales_price)"
        tests:
          - not_null
      - name: old_value
        description: "Previous value before the change (NULL for initial records)"
      - name: new_value
        description: "New value after the change"
      - name: changed_at
        description: "Timestamp when the change was detected (from _sdc_extracted_at)"
        tests:
          - not_null
          
  - name: item_history_view
    description: "User-friendly view of item attribute changes with additional calculations"
    columns:
      - name: item_name
        description: "Name of the item/product"
      - name: sales_description
        description: "Description of the item/product from the products table"
      - name: column_name
        description: "Name of the column that changed"
      - name: old_value
        description: "Previous value before the change"
      - name: new_value
        description: "New value after the change"
      - name: changed_at
        description: "Timestamp when the change was detected"
      - name: numeric_change
        description: "Calculated difference between new and old values for numeric columns"
      - name: percent_change
        description: "Calculated percentage change for price and cost columns"
