version: 2

models:
  - name: orders
    description: "Order information derived from invoices and sales receipts"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: order_number
        description: "Invoice number or Sales Receipt number used as order identifier"
      - name: order_type
        description: "Type of order (invoice or sales_receipt)"
      - name: class
        description: "Class categorization"
      - name: terms
        description: "Payment terms"
      - name: payment_method
        description: "Payment method"
      - name: status
        description: "Order status"
      - name: po_number
        description: "Purchase Order number"
      - name: order_date
        description: "Invoice date or Sales Receipt date (PostgreSQL DATE type)"
      - name: total_amount
        description: "Total amount from invoice or sales receipt"
      - name: company_id
        description: "Reference to companies.company_id, matched using company name heuristics"
        
  - name: order_companies
    description: "Mapping between orders and companies using name matching heuristics"
    columns:
      - name: order_id
        description: "Reference to orders.quickbooks_id"
        tests:
          - not_null
      - name: company_id
        description: "Reference to companies.company_id"
        
  - name: order_items
    description: "Line items from sales receipts and invoices linked to their parent orders"
    columns:
      - name: order_id
        description: "Reference to orders.quickbooks_id"
        tests:
          - not_null
      - name: order_number
        description: "Invoice number or Sales Receipt number"
        tests:
          - not_null
      - name: order_type
        description: "Type of order (invoice or sales_receipt)"
        tests:
          - not_null
      - name: product_code
        description: "Product or service code/name"
      - name: product_description
        description: "Description of the product or service"
      - name: quantity
        description: "Quantity ordered"
      - name: unit_price
        description: "Unit price of the product or service"
      - name: line_amount
        description: "Total amount for this line item"
      - name: product_class
        description: "Classification of the product or service"
      - name: service_date
        description: "Service date if applicable"
      - name: sales_tax_code
        description: "Sales tax code for the product or service"
        
  - name: companies
    description: "Unique company records identified by domain"
    columns:
      - name: company_id
        description: "Surrogate key for the company (MD5 hash of domain)"
        tests:
          - not_null
          - unique
      - name: company_domain
        description: "Domain extracted from email"
      - name: company_name
        description: "Most common company name associated with this domain"
      - name: reference_id
        description: "Reference to a sample QuickBooks ID for this company"
      - name: created_at
        description: "Timestamp when the record was created"
        
  - name: customers
    description: "Customer information with company references"
    columns:
      - name: quickbooks_id
        description: "QuickBooks Internal Id"
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Customer name from CSV"
      - name: first_name
        description: "Customer first name"
      - name: last_name
        description: "Customer last name"
      - name: customer_type
        description: "Type of customer (e.g., Retail, US Customer)"
      - name: company_id
        description: "Reference to companies.company_id"
        
  - name: company_stats
    description: "Aggregated statistics for companies including customer counts and order totals"
    columns:
      - name: company_id
        description: "Reference to companies.company_id"
        tests:
          - not_null
          - unique
      - name: customer_count
        description: "Count of distinct customers associated with this company"
      - name: total_orders
        description: "Sum of all order amounts for this company's customers"
        
  - name: order_matching_stats
    description: "Diagnostic statistics for order-to-company matching"
    columns:
      - name: total_orders
        description: "Total number of orders with non-null amounts"
      - name: matched_orders
        description: "Number of orders that were matched to a company"
      - name: unmatched_orders
        description: "Number of orders that were not matched to a company"
      - name: percent_orders_matched
        description: "Percentage of orders that were matched to a company"
      - name: total_amount
        description: "Total dollar amount of all orders"
      - name: matched_amount
        description: "Total dollar amount of orders matched to companies"
      - name: unmatched_amount
        description: "Total dollar amount of orders not matched to companies"
      - name: percent_amount_matched
        description: "Percentage of total dollar amount that was matched to companies"
      - name: generated_at
        description: "Timestamp when this diagnostic data was generated"
