version: 2

sources:
  - name: raw
    database: mqi  # From meltano.yml config
    schema: raw    # From meltano.yml config
    tables:
      - name: customers
        identifier: customers  # The table name in the database
      - name: invoices
        identifier: invoices
      - name: sales_receipts
        identifier: sales_receipts
      - name: items
        identifier: items
