name: meltano_quickbooks_importer
version: '1.0'
profile: meltano
config-version: 2
require-dbt-version: [">=1.0.0", "<2.0.0"]
flags:
  send_anonymous_usage_stats: False
  use_colors: True
model-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
- seeds
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
log-path: logs
packages-install-path: dbt_packages
clean-targets:
- target
- dbt_packages
- logs
models:
  meltano_quickbooks_importer:
    # Config defaults for all models in this project
    +materialized: view
    # Specific configurations for different model directories
    staging:
      +schema: staging  # Add this line
      +materialized: view
    companies:
      +materialized: table
    customers:
      +materialized: table
    # History tracking models
    item_history:
      +materialized: table

snapshots:
  meltano_quickbooks_importer:
    +target_schema: analytics_snapshots

seeds:
  meltano_quickbooks_importer:
    company_terms:
      +schema: seeds  # Optional, ensures seeds are organized
      +quote_columns: false  # Ensures column names are not quoted
