version: 2

sources:
  - name: raw_data
    schema: raw
    tables:
      - name: customers
        description: "Customer data extracted from QuickBooks"
        columns:
          - name: canonical_name
            description: "Normalized company name"
      - name: items
        description: "Item data extracted from QuickBooks"
      - name: sales_receipts
        description: "Sales receipt data extracted from QuickBooks"
      - name: invoices
        description: "Invoice data extracted from QuickBooks"
